### ISSUE TITLE
Source Distribution is missing Files and Subpackages

### ISSUE THREAD

**Issue by sebuer** [RWTH-EBC/pyCity#258]
The Source Distribution available at https://pypi.org/project/pycity-base/ is missing most python files and also data files. This results in `pip install pycity_base` not installing a working pycity_base project.

https://github.com/RWTH-EBC/richardsonpy has the same issue. As a workaround https://github.com/RWTH-EBC/pyCity/blob/6d897443423830afa460319a6dc2dcebc0f9fe24/.travis.yml#L23-L24 is currently used.

**Comment by ss391347** [comment]
@sebuer: Thanks! I think we can close this issue? :)

**Comment by sebuer** [comment]
@ss391347 Yes, this is fixed by #259.
