### ISSUE TITLE
Rename files absorptionchiller.py, compressionchiller.py, and coolingdevice.py

### ISSUE THREAD

**Issue by ss391347** [RWTH-EBC/pyCity#260]
The given filenames of Python files defining the classes AbsorptionChiller (pycity_base/classes/supply/absorptionchiller.py), CompressionChiller (pycity_base/classes/supply/compressionchiller.py), and CoolingDevice (pycity_base/classes/supply/coolingdevice.py) are not in line with the rest of the pyCity_base package. We should consider renaming them as follows:

absorptionchiller.py -> AbsorptionChiller.py

compressionchiller.py -> CompressionChiller.py

coolingdevice.py -> CoolingDevice.py 

However, this change might have an impact on pyCity_base users!

**Comment by MichaMans** [comment]
@ss391347 I think I tried to use pep8 compliant naming. Could be that this is not what the rest of the code is using. In addition I can still be convicted to misunderstanding the pep8 and of course if it suits more the whole usability of the package I am fine with it

**Comment by ss391347** [comment]
Solved within #239.
